### ISSUE TITLE
Provide fee configuration for named container registration

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1008]
In notary disabled environment, approval of container creation with nice name attribute takes much more additional GAS than other operations (due to NNS invocation). In the testnet we have increased `fee.sidechain`but now side chain economy doesn't work properly. 

The solution is to define separate config record for container creation fee.

```yaml
fee:
  main_chain: 500000000
  side_chain: 1000000000
  named_container_register: 2500000000
```

Use this fee at container approval in Alphabet node.
