### ISSUE TITLE
How can I discover the storage nodes?

### ISSUE THREAD

**Issue by Tasselsd** [nspcc-dev/neofs-node#1113]
How can I discover the storage nodes on mainnet ? So I can find the fastest node to use the neofs grpc api. 

Thanks.

**Comment by alexvanin** [comment]
There are no looking glass \ public monitor service yet to discover list of storage nodes in the network. But there are still ways how you can do that.

1. Start your own storage node (relay mode should be enough) and use control API via `neofs-cli` to fetch current network map.

```yaml
# Example of minimal config to run node in relay mode (without bootstrap)
node:
  wallet:
    path: "./wallet.json"
    address: "NWV1b28F1QiYRNCr1nFJpCWoBBxrYfCfRW"
    password: ""
  addresses:
    - 127.0.0.1:8080
  relay: true
  attribute_0: UN-LOCODE:RU LED
control:
  grpc:
    endpoint: 127.0.0.1:8090
morph: # use side chain RPC endpoints from https://testcdn.fs.neo.org/doc/integrations/endpoints/
  rpc_endpoint:
    - https://rpc1.morph.fs.neo.org:40341
  notification_endpoint:
    - wss://rpc1.morph.fs.neo.org:40341/ws
grpc:
  num: 1
  0:
    endpoint: 127.0.0.1:8080
```

```
$ ./neofs-node -config config.yaml &
[2] 153298

$ neofs-cli control netmap-snapshot --endpoint 127.0.0.1:8090 -w wallet.json 
Node 1: hkBdnnKs9Mcf8bbzjLewvRmf8pNxPcoJopXyN4uMu1Sh ONLINE [/dns4/ingress.jorisnalt.es/tcp/37512]
...
Node 2: nZ9fvRnyE3RRzNW15ar9LFtBLRTkXaGbi9JDSiAPL7UB ONLINE [/dns4/niko.nspcc.ru/tcp/8080]
...
Node 3: qcdkpczLuqhDFbByDRoNRaDfNFGNBB1kZTfNE1cjR8bS ONLINE [/dns4/st3.storage.fs.neo.org/tcp/8080]
...
Node 4: si3kpomg8XzFB733bv92VN6V8biwctb7dY1VL9R5Ukat ONLINE [/dns4/st2.storage.fs.neo.org/tcp/8080]
...
Node 5: tzp2nPka836L56PN4Zyc5iHGQoeE8gYCKK6AwQP6HyZr ONLINE [/dns4/st4.storage.fs.neo.org/tcp/8080]
...
Node 6: 26U53zs4JJpya9StyjLUV1WLUoLbLet63eQjbCKkyt4q1 ONLINE [/dns4/st1.storage.fs.neo.org/tcp/8080]
```

2. Use `netmap` contract in side chain. In general, list of current active storage nodes maintained by network map contract. Invoke [netmap](https://github.com/nspcc-dev/neofs-contract/blob/f530bdf7217a8b5ac1874e227cb0d504056365cb/netmap/netmap_contract.go#L398) method of that contract and decode data as protobuf marshaled [NodeInfo](https://github.com/nspcc-dev/neofs-api/blob/master/netmap/types.proto#L131-L239) message. Network map contract addresses: 
- mainnet: 7c5bdb23e36cc7cce95bf42f3ab9e452c2501df1
- testnet: d4b331639799e2958d4bc5b711b469d79de94e01

List of side chain RPC endpoints is available in the https://testcdn.fs.neo.org/doc/integrations/endpoints/

```
$ neo-go contract testinvokefunction -r https://rpc1.morph.fs.neo.org:40341 7c5bdb23e36cc7cce95bf42f3ab9e452c2501df1 netmap
{
  "state": "HALT",
  "gasconsumed": "5556570",
  "script": "EMAfDAZuZXRtYXAMFPEdUMJS5Lk6L/Rb6czHbOMj21t8QWJ9W1I=",
  "stack": [
    {
      "type": "Array",
      "value": [
        {
          "type": "Struct",
          "value": [
            {
              "type": "ByteString",
              "value": "..."
            }
          ]
        },
        {
          "type": "Struct",
          "value": [
            {
              "type": "ByteString",
              "value": "..."
            }
          ]
        },
        {
          "type": "Struct",
          "value": [
            {
              "type": "ByteString",
              "value": "..."
            }
          ]
        },
        {
          "type": "Struct",
          "value": [
            {
              "type": "ByteString",
              "value": "...
            }
          ]
        },
        {
          "type": "Struct",
          "value": [
            {
              "type": "ByteString",
              "value": "..."
            }
          ]
        },
        {
          "type": "Struct",
          "value": [
            {
              "type": "ByteString",
              "value": "...
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Tasselsd** [comment]
@alexvanin OK，I'll try it now. There are a few questions:

1. What is the responsibility of relay mode node? 
2. Does it use a lot of resources?

**Comment by alexvanin** [comment]
>     1. What is the responsibility of relay mode node?

Storage node in relay mode does not bootstrap to the storage network, it does not allocate local storage resources and does not store any objects. But it still can process incoming requests of NeoFS API or Control API from `neofs-cli`, gateways and other applications.

>     2. Does it use a lot of resources?

It is supposed to be lightweight.

**Comment by Tasselsd** [comment]
> Storage node in relay mode does not bootstrap to the storage network, it does not allocate local storage resources and does not store any objects. But it still can process incoming requests of NeoFS API or Control API from neofs-cli, gateways and other applications.
```
node:
  wallet:
    path: "./wallet.json"
    address: "NWV1b28F1QiYRNCr1nFJpCWoBBxrYfCfRW"
    password: ""
```
@alexvanin in relay mode, this address should have some gas (or side-chain gas) ? If not, can I not configure the wallet section?
