### ISSUE TITLE
Minimal config to run Storage node in relay mode

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1114]
Related to https://github.com/nspcc-dev/neofs-node/issues/1113

To start storage node in relay mode I expect to use such minimal config

```yaml
node:
  wallet:
    path: "./wallet.json"
    address: "NWV1b28F1QiYRNCr1nFJpCWoBBxrYfCfRW"
    password: ""
  relay: true

grpc:
  num: 1
  0:
    endpoint: 127.0.0.1:8080

control:
  grpc:
    endpoint: 127.0.0.1:8090

morph:
  rpc_endpoint:
    - https://rpc1.morph.fs.neo.org:40341
  notification_endpoint:
    - wss://rpc1.morph.fs.neo.org:40341/ws
```

However such config won't work with neofs-node v0.27.4
1. Node expects a list of bootstrap addresses
2. Node expects UN-LOCODE attribute

I think both should be optional when node starts in relay mode. Thoughts?
