### ISSUE TITLE
[bug in v0.27.5]: `--ir` key for control API isn't available in config

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1166]
When I request healthcheck info from Control API with in Inner Ring node, CLI fails. To make it work, I need to provide `--ir` key from command line. 

## Expected Behavior

I expect that I can specify `ir: true` key in config
```
user@host ~ # cat  control.yml
endpoint: [localhost:8090](http://localhost:8090/)
wallet: /path/to/wallet.json
password: ***
ir: true

user@host ~ # /usr/local/bin/neofs-cli control healthcheck -c control.yml
Health status: READY
```

## Current Behavior
The response I get with the above config
```
user@host ~ # /usr/local/bin/neofs-cli control healthcheck -c control.yml
rpc error: rpc error: code = Unimplemented desc = unknown service control.ControlService
```
Response is ok when I use `--ir` key
```
user@host ~ # neofs-cli control healthcheck --config control.yml --ir
Health status: READY
``` 

## Your Environment
```
user@host ~ # /usr/local/bin/neofs-cli --version
Version: v0.27.5 
Build: 2022-01-31T11:48:11+00:00 
Debug: false
```

**Comment by carpawell** [comment]
That is because of the missing `viper` -> `cobra` flag binding. The important thing about this is that it is not the only example of that, there are more config flags that are not available via a config file. I think it makes sense to fix all of them with that issue.

**Comment by alexvanin** [comment]
I don't think it is a bug, because CLI does not declare that all command line flags are available from config. I propose to finish https://github.com/nspcc-dev/neofs-node/issues/1103 by adding config example in the repo and close this issue.

```yaml
wallet: <>       # path to the NEP-6 wallet file or path to the binary encoded private key file or WIF
address: <>      # address in NEP-6 wallet, empty for default 
password: <>     # password from NEP-6 wallet
rpc-endpoint: <> # endpoint for NeoFS API commands
endpoint: <>     # endpoint for NeoFS Control API commands
```
