### ISSUE TITLE
access to operation PUT is denied by basic ACL check

### ISSUE THREAD

**Issue by jisnardo** [nspcc-dev/neofs-node#1179]
Hi,

after upgrading from 0.27.4 to 0.27.5 logs complain about this:

```
Attaching to neofs_mainnet
neofs_mainnet    | 2022-02-13T15:18:09.556Z    info    neofs-node/config.go:344    shard attached to engine    {"id": "39jizZjPYUEcDsxarNtUBQ"}
neofs_mainnet    | 2022-02-13T15:18:10.329Z    info    neofs-node/netmap.go:239    initial network state    {"epoch": 4615, "state": "UNSPECIFIED"}
neofs_mainnet    | 2022-02-13T15:18:11.271Z    info    neofs-node/morph.go:205    websocket neo event listener established    {"endpoint": "wss://rpc3.morph.fs.neo.org:40341/ws"}
neofs_mainnet    | 2022-02-13T15:18:11.271Z    info    neofs-node/grpc.go:82    start listening gRPC endpoint    {"endpoint": "[::]:37512"}
neofs_mainnet    | 2022-02-13T15:18:11.582Z    info    replicator/process.go:20    process routine    {"component": "Object Replicator", "task queue capacity": 0, "put timeout": 5}
neofs_mainnet    | 2022-02-13T15:18:11.741Z    info    neofs-node/main.go:99    application started    {"build_time": "now", "version": "v0.27.5", "debug": "false"}
neofs_mainnet    | 2022-02-13T15:18:13.453Z    error    replicator/process.go:82    could not replicate object    {"component": "Object Replicator", "node": "03aeff8a19f0202090afb0916b1c00b432321be7e8623a06c9b9b5db8ee5c053a4", "object": "Hh6qJ2Fa9WzSK7PESResS4mmuoZ2a47Z7F6ZvmR7AEHU/HXENvZdWwgxRuq8QXQJNtdPxdbfYNntNuKg55Wti
Kf4n", "error": "(*putsvc.RemoteSender) could not send object: (*putsvc.remoteTarget) could not put object to [/dns4/st1.storage.fs.neo.org/tcp/8080]: status: code = 1024 message = (*response.ClientMessageStreamer) could not send the request: access to operation PUT is denied by basic ACL check"}
```

```
root@host:~/neofs/setup/bin# ./neofs-cli-amd64-v0.27.5 control healthcheck -w ../mainnet/private.key --endpoint 127.0.0.1:17512 -v
Network status: STATUS_UNDEFINED
Health status: READY
```

Any suggestion will be appreciated.

**Comment by jisnardo** [comment]
@alexvanin any suggestion? Thanks in advance.

**Comment by cthulhu-rider** [comment]
@jisnardo is this the same node https://github.com/nspcc-dev/neofs-node/issues/1178? We need the configuration here to figure out the reason, too.

**Comment by jisnardo** [comment]
Hi @cthulhu-rider,

are diefrent nodes, testnet / mainnet.

This is config for mainnet:

```
node:
  key: /private.key # path to a binary private key
  addresses: # list of addresses announced by Storage node in the Network map
    - ingress.jorisnalt.es:37512
  attribute_0: User-Agent:NeoFS v0.27.5
  attribute_1: UN-LOCODE:ES VLC
  attribute_2: Capacity:1TB
  attribute_3: Price:100

grpc:
  num: 1 # total number of listener endpoints
  0:
    endpoint: 0.0.0.0:37512 # endpoint for gRPC server
    tls:
      enabled: false # use TLS for a gRPC connection

metrics:
  address: 127.0.0.1:9090 # endpoint for Node metrics
  shutdown_timeout: 15s # timeout for metrics HTTP server graceful shutdown

storage:
  shard_num: 1 # total number of shards
  shard:
    0:
      metabase:
        path: /storage/metabase # metabase path
        perm: 0644 # permissions for metabase files (directories: +x for current user and group)
      blobstor:
        path: /storage/blobstor # blobstor path
        perm: 0644 # permissions for blobstor files (directories: +x for current user and group)
        blobovnicza:
          opened_cache_capacity: 32 # maximum number of opened database files
          depth: 1 # max depth of object tree storage in key-value DB
          width: 1 # max width of object tree storage in key-value DB
      writecache: # use write-cache
        enabled: false
      gc:
        remover_batch_size: 100 # number of objects to be removed by the garbage collector
        remover_sleep_interval: 1m # frequency of the garbage collector invocation

object:
  put:
    pool_size_remote: 100 # number of async workers for remote PUT operations
    pool_size_local: 100

morph:
  rpc_endpoint: # side chain NEO RPC endpoints; are shuffled and used one by one until the first success
    - https://rpc1.morph.fs.neo.org:40341
    - https://rpc2.morph.fs.neo.org:40341
    - https://rpc3.morph.fs.neo.org:40341
    - https://rpc4.morph.fs.neo.org:40341
    - https://rpc5.morph.fs.neo.org:40341
    - https://rpc6.morph.fs.neo.org:40341
    - https://rpc7.morph.fs.neo.org:40341
  notification_endpoint: # side chain NEO RPC notification endpoints; are shuffled and used only the first non-error one
    - wss://rpc1.morph.fs.neo.org:40341/ws
    - wss://rpc2.morph.fs.neo.org:40341/ws
    - wss://rpc3.morph.fs.neo.org:40341/ws
    - wss://rpc4.morph.fs.neo.org:40341/ws
    - wss://rpc5.morph.fs.neo.org:40341/ws
    - wss://rpc6.morph.fs.neo.org:40341/ws
    - wss://rpc7.morph.fs.neo.org:40341/ws
  dial_timeout: 20s # timeout for side chain NEO RPC client connection

contracts: # side chain NEOFS contract script hashes; optional, override values retrieved from NNS contract
  balance: dc1ec98d9d0c5f9dfade16144defe08cffc5ca55
  container: 1b6e68d299b570e1cb7e86eadfdc06aa2e8e0cc5
  netmap: 7c5bdb23e36cc7cce95bf42f3ab9e452c2501df1
  reputation: 7ad824fd1eeb1565be2cee3889214b9aa605d2fc

logger:
  level: info # logger level: one of "debug", "info" (default), "warn", "error", "dpanic", "panic", "fatal"

control:
  authorized_keys: # list of hex-encoded public keys that have rights to use the Control Service
  grpc:
    endpoint: 0.0.0.0:17512 # endpoint that is listened by the Control Service
```
