### ISSUE TITLE
Refactor blobstor configuration

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1522]
Make blobstor configuration contain multiple same-level "blobstors", each with it's own policy.
```
blobstor:
  -  type: blobovnicza.tree
     path: /srv/neofs/small0
     size: 4g
     depth: 1
     width: 4
     opened_cache_capacity: 50
     policy:
       max_object_size: 1024k
  -  type: fstree
     path: /srv/neofs/big0
     compress: true
     perm: 0644
     depth: 5
```

- [x] #1523
- [x] #1524
- [x] #1525
- [x] #1526
- [ ] #1527
- [ ] #1528
