### ISSUE TITLE
Specify pool of NEO endpoints in config

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#157]
Both inner ring and storage node configurations have NEO endpoint fields. It would be nice to support pool of addresses.

```yaml
# Pure YAML:
morph:
  endpoint: 
    - https://morph1.nspcc.ru
    - https://morph2.nspcc.ru
    - https://morph3.nspcc.ru

# With ENV support:
morph:
  endpoint_0: https://morph1.nspcc.ru
  endpoint_1: https://morph2.nspcc.ru
  endpoint_2: https://morph3.nspcc.ru

# With priorities:
morph:
  endpoint_0: 
    url: https://morph1.nspcc.ru
    priority: 1.0
  endpoint_1: 
    url: https://morph2.nspcc.ru
    priority: 0.5
  endpoint_2: 
    url: https://morph3.nspcc.ru
    priority: 0.5
```

Neofs-node can choose random address and use it in runtime if it is active. This way we can uniformly distribute load of RPC nodes that will be present in preinstalled configuration.

### What's wrong with runtime connection pool?
Instead of choosing one active address before startup, neofs-node can keep pool of active connections, healthcheck it in runtime and rotate connections whenever it needs. This increases stability of RPC node failures but there is a tricky part.

While connection pool works fine with clients, neofs-node also uses event listener to fetch new notifications from blockchain. Therefore neofs-node should multiplex several listeners to provide single stable channel of events. This is not trivial task and requires connections to several RPC nodes simultaneously. The other option: rotate listeners the same way as client connection, but we can have a bit of downtime during rotation, which is bad.

So the convenient way to address this problem: choose one endpoint and work with it. As soon as there are problems listener will close connection and client will return an error. In this case we can restart / reinitialize application with new single RPC endpoint.
