### ISSUE TITLE
Support templates in shard config

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1807]
Read the shard number in the config and create that number of shards with a template config that supports number substitution.
Example:

```yaml
shard:
  template:
    number: 1
    metabase:
      path: '/path/meta/metabase{{ INDEX }}.db'
```

It also could have not only shard number var.
