### ISSUE TITLE
Need to make process of verify node config more intelligent

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#1950]
I have case with mistake in config, which lead to part of config was not used.
Config with mistake: 
```
storage:
    shard:
        0:
            blobstor:
            -   path: /srv/neofs/data0/blobovnicza
                type: blobovnicza
            -   path: /srv/neofs/data0
                type: fstree
            default:
                blobstor:
                -   depth: 1
                    opened_cache_capacity: 32
                    perm: '0644'
                    size: 512mb
                    width: 4
                -   depth: 4
                    perm: '0644'
                compress: true
                compression_exclude_content_types:
                - audio/*
                - video/*
                gc:
                    remover_batch_size: 1000
                    remover_sleep_interval: 10s
                metabase:
                    max_batch_delay: 20ms
                    max_batch_size: 1000
                    perm: '0644'
                pilorama:
                    max_batch_delay: 5ms
                    max_batch_size: 500
                    no_sync: false
                resync_metabase: true
                small_object_size: 128 kb
                writecache:
                    capacity: 3gb
                    enabled: true
                    max_object_size: 8mb
                    memcache_capacity: 1gb
                    small_object_size: 128kb
                    workers_number: 30
            metabase:
                path: /srv/neofs/meta0/metabase0.db
            pilorama:
                path: /srv/neofs/meta0/pilorama0.db
            writecache:
                path: /srv/neofs/meta0/write_cache0
```
In this case ```default:``` section was in the ```shard.0``` section. But it should be at the same level. This mistake have lead to ``default``` section was ignored by node.

We should make the process of verify node config more intelligent.
