### ISSUE TITLE
Big object wasn't deleted properly. Object search return REGULAR object type instead of TOMBSTONE after object was removed.

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#2053]
## Steps to Reproduce (for bugs)
1.Create container
2.Upload complex object
3.Delete object
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/wallet_config.yml object delete --rpc-endpoint '172.26.161.66:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/TemporaryDir/2c76a8f0-b2a8-478a-856a-ac1800c8cd05.json' --cid '667WmBtecHcGqqu3jfxbVra7h7FfugQXYoef192JZXNG' --oid 'FQivqT3vjXTH9SRkwG54CZRbLQQdF3YFWJwWaMk4vAeW'
RETCODE: 0

STDOUT:
Object removed successfully.
  ID: FxxKcp94c94mewsEQ6RUgBXrGZqZMsQs2gXjedKDuFuF
  CID: 667WmBtecHcGqqu3jfxbVra7h7FfugQXYoef192JZXNG

STDERR:

Start / End / Elapsed	 03:01:08.351752 / 03:01:08.932780 / 0:00:00.581028
```
4.Check that objects was removed
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/wallet_config.yml object get --rpc-endpoint '172.26.161.255:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/TemporaryDir/2c76a8f0-b2a8-478a-856a-ac1800c8cd05.json' --cid '667WmBtecHcGqqu3jfxbVra7h7FfugQXYoef192JZXNG' --oid 'FQivqT3vjXTH9SRkwG54CZRbLQQdF3YFWJwWaMk4vAeW' --file 'TemporaryDir/9e36b8ff-3cb9-4568-add9-557457749d4d' --no-progress
RETCODE: 1

STDOUT:
rpc error: read object header: status: code = 2052 message = object already removed
STDERR:

Start / End / Elapsed	 03:01:27.911276 / 03:01:28.694309 / 0:00:00.783033
```
5.Check that container does not contain root objects
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/wallet_config.yml object search --rpc-endpoint '172.26.161.66:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/TemporaryDir/2c76a8f0-b2a8-478a-856a-ac1800c8cd05.json' --cid '667WmBtecHcGqqu3jfxbVra7h7FfugQXYoef192JZXNG' --root
RETCODE: 0

STDOUT:
Found 0 objects.

STDERR:

Start / End / Elapsed	 03:01:28.696452 / 03:01:29.078474 / 0:00:00.382022
```
6.Get PHY objects from container
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/wallet_config.yml object search --rpc-endpoint '172.26.161.66:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/TemporaryDir/2c76a8f0-b2a8-478a-856a-ac1800c8cd05.json' --cid '667WmBtecHcGqqu3jfxbVra7h7FfugQXYoef192JZXNG' --phy
RETCODE: 0

STDOUT:
Found 6 objects.
AKC4Yxo2vY232XhzQLi6633oYB9fBaz24mu61hSc9HKf
636WrfhSvDN3EzzYdPo3pf9gqGKg5zivoRrncyv3BeoP
FxxKcp94c94mewsEQ6RUgBXrGZqZMsQs2gXjedKDuFuF
GaiMvcs8V4s4g7xSMYJBiZ3i6nxBgEPVt5RtrnCRYJPw
43CrU3aPR2fnmAquppiVM3s65ksC6BXthiN6Dzm6QLSi
CcGX9xCLBquyGE9aQbeZFaimN6hEnnpLEwLUTmixs1h8

STDERR:

Start / End / Elapsed	 03:01:29.080397 / 03:01:29.462768 / 0:00:00.382371
```
7.Check that those objects are TOMBSTONE objects. But actually object AKC4Yxo2vY232XhzQLi6633oYB9fBaz24mu61hSc9HKf has type REGULAR but we expect TOMBSTONE
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/wallet_config.yml object head --rpc-endpoint '172.26.161.66:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.YvrfcHQ4A9/neofs-testcases/TemporaryDir/2c76a8f0-b2a8-478a-856a-ac1800c8cd05.json' --cid '667WmBtecHcGqqu3jfxbVra7h7FfugQXYoef192JZXNG' --oid 'AKC4Yxo2vY232XhzQLi6633oYB9fBaz24mu61hSc9HKf' --json
RETCODE: 0

STDOUT:
{"objectID":{"value":"imIk1IYkPY+esga98spaV0W8tgc0uPwLp+4YLRlzDIo="},"signature":{"key":"AqKtGnLURKSdh7+0FA38L5HahKBxi49VpRCAwxR0C9Zi","signature":"BMHzRRpC36l/qyEqPdfz3XkGvcgdgr1OUBQLTd+9LhOi4oOPvjknJ5BnRYBym6Qs9mMe2XI5P+mMwYvZflPw1/I=","scheme":"ECDSA_SHA512"},"header":{"version":{"major":2,"minor":13},"containerID":{"value":"S5mz/o1VwxsFhTedpJCPeTpPd83sLjpPfZ5hFE2Ikbk="},"ownerID":{"value":"NQmauoBV5hcZIyqlPei5fJx5ZkAuPfNR+g=="},"creationEpoch":"6","payloadLength":"13421728","payloadHash":{"type":"SHA256","sum":"A4XmVKARBm5leZQaR4Ix7iaMxfs6AZLno7t15Mf1Rlc="},"objectType":"REGULAR","homomorphicHash":null,"sessionToken":{"body":{"id":"ycEdhFXOSuSd4cotHjFkaQ==","ownerID":{"value":"NQmauoBV5hcZIyqlPei5fJx5ZkAuPfNR+g=="},"lifetime":{"exp":"16","nbf":"6","iat":"6"},"sessionKey":"AqKtGnLURKSdh7+0FA38L5HahKBxi49VpRCAwxR0C9Zi","object":{"verb":"PUT","target":{"container":{"value":"S5mz/o1VwxsFhTedpJCPeTpPd83sLjpPfZ5hFE2Ikbk="},"objects":[]}}},"signature":{"key":"AwHq7fwY916il991eF5l4NyPcff0lagQtfalEFTmBS93","signature":"BM81ppeHeyLaaFh5YSRnYCQy/ELaJLHX25dAGzSh0i9sr56R2C/lJLecfeILnFMKdxn3S8U/OMAHr9HCEOjZTgo=","scheme":"ECDSA_SHA512"}},"attributes":[],"split":{"parent":null,"previous":null,"parentSignature":null,"parentHeader":null,"children":[],"splitID":"cZl5CniySiaKoxMJGHnvmA=="}},"payload":""}

STDERR:

Start / End / Elapsed	 03:01:29.464484 / 03:01:29.895099 / 0:00:00.430615
```

**Node logs:** [7bdc1ba49fba7ee.zip](https://github.com/nspcc-dev/neofs-node/files/10003759/7bdc1ba49fba7ee.zip)
**Test log:** [c5b633dccb7fb8.zip](https://github.com/nspcc-dev/neofs-node/files/10003765/c5b633dccb7fb8.zip)

**Versions:**
```
NeoFS node 0.34.0-40-gcdbfd057
```
## Your Environment
Server setup and configuration:
cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw

Operating System and version (uname -a):
linux vedi 5.10.0-16-amd64 https://github.com/nspcc-dev/neofs-node/issues/1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
