### ISSUE TITLE
neofs-cli --root returns already removed object

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#2067]
## Expected Behavior
neofs-cli --root should not returns already removed object

## Current Behavior
neofs-cli --root returns already removed object

## Steps to Reproduce (for bugs)
1.Delete object
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/wallet_config.yml object delete --rpc-endpoint '172.26.160.159:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/TemporaryDir/68d7f281-d724-46e0-b5fd-28d5b08a7962.json' --cid '7aiAVVEK5i6MexJ2Hsd5QVK4AYJoJ2TDDhsuGCwa6BFS' --oid '9mpVkHhZW22DBJvqK9q9Q7ibHZT23xNawamhaUC7t79H'
RETCODE: 0

STDOUT:
Object removed successfully.
  ID: CSwCyxbYmByX7j7wdVHD4DP5T25ag5B81VnBx4LD3pPW
  CID: 7aiAVVEK5i6MexJ2Hsd5QVK4AYJoJ2TDDhsuGCwa6BFS

STDERR:

Start / End / Elapsed	 03:01:05.029516 / 03:01:05.500538 / 0:00:00.471022
```
2.Check that object tombstone exist
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/wallet_config.yml object head --rpc-endpoint '172.26.160.159:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/TemporaryDir/68d7f281-d724-46e0-b5fd-28d5b08a7962.json' --cid '7aiAVVEK5i6MexJ2Hsd5QVK4AYJoJ2TDDhsuGCwa6BFS' --oid 'CSwCyxbYmByX7j7wdVHD4DP5T25ag5B81VnBx4LD3pPW' --json
RETCODE: 0

STDOUT:
{"objectID":{"value":"qhVeNUAJZiUlEOMkc/HWKyZRI8s0t0kCHfxWJMovauU="}, "signature":{"key":"Aky20a5v3htDboTHHvHerXjZKWqYGd+uJIl5OHu4Csi3", "signature":"BDm3FyM+lioD/sVfw0tJpYnKM+qQZ3Gc+0CO4NFWQvQ/ikWWKtjlbNLZfySyJhFRGo8hPuYxJoum2/U8m2DK2Ls=", "scheme":"ECDSA_SHA512"}, "header":{"version":{"major":2, "minor":13}, "containerID":{"value":"YcjVBsEcbX/gITIieE1i9SiUd6+sDVFUDxPPrY8gcoU="}, "ownerID":{"value":"NRo8Kipysxhis7EXCpX/HzBYpX4Yum9MiA=="}, "creationEpoch":"5", "payloadLength":"38", "payloadHash":{"type":"SHA256", "sum":"56RWiDD9wjFj2bKA8wm5JoDQmT7Z1HggNnXTmbBYgXQ="}, "objectType":"TOMBSTONE", "homomorphicHash":null, "sessionToken":{"body":{"id":"u0qr4x5eRtGQI5ZCAKA3EQ==", "ownerID":{"value":"NRo8Kipysxhis7EXCpX/HzBYpX4Yum9MiA=="}, "lifetime":{"exp":"15", "nbf":"5", "iat":"5"}, "sessionKey":"Aky20a5v3htDboTHHvHerXjZKWqYGd+uJIl5OHu4Csi3", "object":{"verb":"DELETE", "target":{"container":{"value":"YcjVBsEcbX/gITIieE1i9SiUd6+sDVFUDxPPrY8gcoU="}, "objects":[{"value":"gljBJgRIkblOWGc2NF10EJfXLEBVT/LYNNTATJ1NKjA="}]}}}, "signature":{"key":"A0Ko7AbWaKgCKFojsjzUFtAqJICZl7dlhGPKT2hoxxo7", "signature":"BEU/WEJmtqrJTA/XBJYOh11BYt8zzCN+FARleGMzFYXusXYmMFR0yEuYGPBQE8GpVCHw/vZVbgFfr/gLy6ZRW1E=", "scheme":"ECDSA_SHA512"}}, "attributes":[{"key":"__NEOFS__EXPIRATION_EPOCH", "value":"10"}], "split":null}, "payload":""}

STDERR:

Start / End / Elapsed	 03:01:05.502304 / 03:01:05.876050 / 0:00:00.373746
```
3.Check that GET object not returned object
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/wallet_config.yml object get --rpc-endpoint '172.26.162.148:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/TemporaryDir/68d7f281-d724-46e0-b5fd-28d5b08a7962.json' --cid '7aiAVVEK5i6MexJ2Hsd5QVK4AYJoJ2TDDhsuGCwa6BFS' --oid '9mpVkHhZW22DBJvqK9q9Q7ibHZT23xNawamhaUC7t79H' --file 'TemporaryDir/eada9e56-d8e0-4df6-9902-e4936d9f39a2' --no-progress
RETCODE: 1

STDOUT:
rpc error: read object header: status: code = 2052 message = object already removed
STDERR:

Start / End / Elapsed	 03:01:26.373416 / 03:01:27.119231 / 0:00:00.745815
```
4.SEARCH with --root in container on the same node as we had removed object previously returns removed object  
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/wallet_config.yml object search --rpc-endpoint '172.26.160.159:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests/tmp.GGFBNtcNyK/neofs-testcases/TemporaryDir/68d7f281-d724-46e0-b5fd-28d5b08a7962.json' --cid '7aiAVVEK5i6MexJ2Hsd5QVK4AYJoJ2TDDhsuGCwa6BFS' --root
RETCODE: 0

STDOUT:
Found 1 objects.
9mpVkHhZW22DBJvqK9q9Q7ibHZT23xNawamhaUC7t79H

STDERR:

Start / End / Elapsed	 03:01:27.121423 / 03:01:27.499608 / 0:00:00.378185
```
**Node logs:**[472685ed2057e4ac.zip](https://github.com/nspcc-dev/neofs-node/files/10028629/472685ed2057e4ac.zip)
**Test log:**[7d65cc53eb65b48c.zip](https://github.com/nspcc-dev/neofs-node/files/10028631/7d65cc53eb65b48c.zip)
**Version:**
```
NeoFS node 0.34.0-54-g402bbba1
```
**Your Environment**
Server setup and configuration:
cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw

Operating System and version (uname -a):
linux vedi 5.10.0-16-amd64 https://github.com/nspcc-dev/neofs-node/issues/1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
