### ISSUE TITLE
Deleted COMPLEX object can be found in container (neofs-cli object search --root)

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#2236]
This was autimatic test ```testsuites.object.test_object_api.TestObjectApi#test_object_search_should_return_tombstone_items```

## Expected Behavior
Deleted object can't be found in container using following 'neofs-cli object search --root' command

## Current Behavior
Deleted object can found in container using following 'neofs-cli object search --root' command

## Steps to Reproduce (for bugs)
1. Create container 
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/wallet_config.yml container create --rpc-endpoint '172.26.160.65:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/TemporaryDir/9bcffd0e-41c4-41d1-9ec5-0958978c796a.json' --await --policy 'REP 2 IN X CBF 1 SELECT 4 FROM * AS X'
RETCODE: 0

STDOUT:
container ID: AH45mvzjKeZM8rhnBFyEYwQm3nhnDq8aHM6sWpLS5MXb
awaiting...
container has been persisted on sidechain

STDERR:

Start / End / Elapsed	 02:46:07.337448 / 02:46:16.771931 / 0:00:09.434483
```
2. Put object
```
OMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/wallet_config.yml object put --rpc-endpoint '172.26.160.217:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/TemporaryDir/9bcffd0e-41c4-41d1-9ec5-0958978c796a.json' --cid 'AH45mvzjKeZM8rhnBFyEYwQm3nhnDq8aHM6sWpLS5MXb' --file '/jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/TemporaryDir/5124e4d3-b48f-45cc-bcb4-f5d08a7096d2' --no-progress
RETCODE: 0

STDOUT:
[/jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/TemporaryDir/5124e4d3-b48f-45cc-bcb4-f5d08a7096d2] Object successfully stored
  OID: CbQRbMSr7p4iYpWoJGx1m7mHrVjwkP6yMkfGsdKRJSmF
  CID: AH45mvzjKeZM8rhnBFyEYwQm3nhnDq8aHM6sWpLS5MXb

STDERR:

Start / End / Elapsed	 02:46:19.091844 / 02:46:46.512955 / 0:00:27.421111
```
3. Delete object
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/wallet_config.yml object delete --rpc-endpoint '172.26.160.65:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/TemporaryDir/9bcffd0e-41c4-41d1-9ec5-0958978c796a.json' --cid 'AH45mvzjKeZM8rhnBFyEYwQm3nhnDq8aHM6sWpLS5MXb' --oid 'CbQRbMSr7p4iYpWoJGx1m7mHrVjwkP6yMkfGsdKRJSmF'
RETCODE: 0

STDOUT:
Object removed successfully.
  ID: 5gd9KJDhA6WyGAM6DiHf6LTYrqVqc77nxgSP4pUsuEQS
  CID: AH45mvzjKeZM8rhnBFyEYwQm3nhnDq8aHM6sWpLS5MXb

STDERR:

Start / End / Elapsed	 02:46:46.892286 / 02:46:47.381903 / 0:00:00.489617
```
4. Tick epoch
```
HOST: 172.26.160.65
COMMAND:
 sudo neofs-adm --config /home/service/config.yaml morph force-new-epoch 
RC:
 0
STDOUT:
 Current epoch: 14, increase to 15.
 Waiting for transactions to persist...

STDERR:

Start / End / Elapsed	 02:46:48.579874 / 02:46:59.798878 / 0:00:11.219004
```
5. Verify that object was deleted
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/wallet_config.yml object get --rpc-endpoint '172.26.160.65:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/TemporaryDir/9bcffd0e-41c4-41d1-9ec5-0958978c796a.json' --cid 'AH45mvzjKeZM8rhnBFyEYwQm3nhnDq8aHM6sWpLS5MXb' --oid 'CbQRbMSr7p4iYpWoJGx1m7mHrVjwkP6yMkfGsdKRJSmF' --file 'TemporaryDir/dd103149-ae35-46a8-a82c-499f6e46145e' --no-progress
RETCODE: 1

STDOUT:
rpc error: read object header: status: code = 2052 message = object already removed

STDERR:

Start / End / Elapsed	 02:47:09.810446 / 02:47:10.214905 / 0:00:00.404459
```
6. Try to find deleted object
```
COMMAND: neofs-cli --config /jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/wallet_config.yml object search --rpc-endpoint '172.26.160.65:8080' --wallet '/jenkins/workspace/sbercloud_functional_tests_nightly/tmp.kS0mwg7qzZ/neofs-testcases/TemporaryDir/9bcffd0e-41c4-41d1-9ec5-0958978c796a.json' --cid 'AH45mvzjKeZM8rhnBFyEYwQm3nhnDq8aHM6sWpLS5MXb' --root
RETCODE: 0

STDOUT:
Found 1 objects.
CbQRbMSr7p4iYpWoJGx1m7mHrVjwkP6yMkfGsdKRJSmF

STDERR:

Start / End / Elapsed	 02:47:10.217638 / 02:47:10.593170 / 0:00:00.375532
```

## Version
```
0.35.0-28-gb6c63173-dirty
```
## Node Logs 
[172.26.160.65-log.txt.zip](https://github.com/nspcc-dev/neofs-node/files/10578081/172.26.160.65-log.txt.zip)
## Test logs 
[b881a515ce8ce1b6.zip](https://github.com/nspcc-dev/neofs-node/files/10578061/b881a515ce8ce1b6.zip)

## Your Environment
Server setup and configuration:
Virtual, 4 servers, 4 SN, 4 http qw, 4 s3 gw

Operating System and version (uname -a):
linux vedi 5.10.0-16-amd64 https://github.com/nspcc-dev/neofs-node/issues/1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux
