### ISSUE TITLE
We cannot GET object from node which not included in container

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#2269]
If we try to GET object from node which not included in container we have error `Object not found`.
This bug found in autotest `testsuites.network.test_node_management.TestNodeManagement#test_drop_object`

## Expected Behavior
We should GET object from any node even it not included in container.

## Current Behavior
If we try to GET object from node which not included in container we have error `Object not found`.

## Steps to Reproduce (for bugs)
1.Create container
```
COMMAND: neofs-cli --config /home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/wallet_config.yml container create --rpc-endpoint 'obj-nn-test-node2.spb.yadro.com:8081' --wallet '/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/da84875f-6eab-4491-adb9-ce79af5e4557.json' --await --policy "REP 1 CBF 1 SELECT 1 FROM * FILTER 'UN-LOCODE' EQ 'SE STO' AS LOC"
RETCODE: 0

STDOUT:
container ID: BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm
awaiting...
container has been persisted on sidechain

STDERR:

Start / End / Elapsed	 04:04:03.070790 / 04:04:04.487075 / 0:00:01.416285
```
2.PUT 2 objects
```
COMMAND: neofs-cli --config /home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/wallet_config.yml object put --rpc-endpoint 'obj-nn-test-node2.spb.yadro.com:8084' --wallet '/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/da84875f-6eab-4491-adb9-ce79af5e4557.json' --cid 'BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm' --file '/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/81ec7fcc-b9de-45b1-82ca-804d6930d9d4' --no-progress
RETCODE: 0

STDOUT:
[/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/81ec7fcc-b9de-45b1-82ca-804d6930d9d4] Object successfully stored
  OID: 8UPf7oaUGumJTcS8qxB5eSUzxhDx9TEJAjJ4UhcQyVDT
  CID: BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm

STDERR:

Start / End / Elapsed	 04:04:04.931340 / 04:04:05.372115 / 0:00:00.440775
```
```
COMMAND: neofs-cli --config /home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/wallet_config.yml object put --rpc-endpoint 'obj-nn-test-node2.spb.yadro.com:8082' --wallet '/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/da84875f-6eab-4491-adb9-ce79af5e4557.json' --cid 'BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm' --file '/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/0ed06de5-491a-4f2b-8838-f2f4c131fe9c' --no-progress
RETCODE: 0

STDOUT:
[/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/0ed06de5-491a-4f2b-8838-f2f4c131fe9c] Object successfully stored
  OID: 8w7BYQAfbvsPikveTuMvgWc8L3X1giSxJdGkqCgwj78A
  CID: BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm

STDERR:

Start / End / Elapsed	 04:04:05.381765 / 04:04:06.029920 / 0:00:00.648155
```
3.Try to GET first object with sucess
```
COMMAND: neofs-cli --config /home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/wallet_config.yml object get --rpc-endpoint 'obj-nn-test-node2.spb.yadro.com:8081' --wallet '/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/da84875f-6eab-4491-adb9-ce79af5e4557.json' --cid 'BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm' --oid '8UPf7oaUGumJTcS8qxB5eSUzxhDx9TEJAjJ4UhcQyVDT' --file 'TemporaryDir/d53baae1-a8ae-47ce-956b-fcb85a2adcb3' --no-progress
RETCODE: 0

STDOUT:
[TemporaryDir/d53baae1-a8ae-47ce-956b-fcb85a2adcb3] Object successfully saved
ID: 8UPf7oaUGumJTcS8qxB5eSUzxhDx9TEJAjJ4UhcQyVDT
CID: BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm
Owner: NTb6VN1CySB4iUAeFPrR9i3ezoEJ51AHqi
CreatedAt: 142
Size: 1000
HomoHash: 4b7350d9ba6b0d66f80c95ddbaa0e8500de90896d96d2726cacb75229dafcd536666781afc33004d566b26aa10de5ed27c81ad4b0ba6f5ec60e5d6d81a2889dc
Checksum: 0798dfdef6047a17748d763d71df25f6cde30307c37dbee14f46c49c9140dd07
Type: REGULAR
Attributes:
  FileName=81ec7fcc-b9de-45b1-82ca-804d6930d9d4
  Timestamp=1676952245 (2023-02-21 04:04:05 +0000 UTC)
ID signature:
  public key: 024802e55366bd50fa0104fa9274c897e505e59264adf394d1944b8dcb896e2b83
  signature: 04c4f0905e2deccb54c357c4e9c760241d80887dd4956642bef4fc89546ac3cc67fa154659b220a8b1a313450d5e8bd2de9e03b4e9fb49932ae98a9b8e6b2392fc

STDERR:

Start / End / Elapsed	 04:04:06.037778 / 04:04:06.480412 / 0:00:00.442634
```
4.Try to GET second object with error
```
COMMAND: neofs-cli --config /home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/wallet_config.yml object get --rpc-endpoint 'obj-nn-test-node2.spb.yadro.com:8083' --wallet '/home/ci/jenkins_home/workspace/neofs-testcases_run/tmp.i2qOafSFtF/neofs-testcases/TemporaryDir/da84875f-6eab-4491-adb9-ce79af5e4557.json' --cid 'BkJMD9xQoPCBjsyQgWnW8WaguCKrFP6Ukd4J1NMLyxEm' --oid '8w7BYQAfbvsPikveTuMvgWc8L3X1giSxJdGkqCgwj78A' --file 'TemporaryDir/d6e5fdc1-7d4e-4c83-95e8-d03b3a7b227d' --no-progress
RETCODE: 1

STDOUT:
rpc error: read object header: status: code = 2049 message = object not found

STDERR:

Start / End / Elapsed	 04:04:06.897656 / 04:04:07.382074 / 0:00:00.484418
```
## Logs
[obj-nn-test-node2.spb.yadro.com-s01-log.txt.zip](https://github.com/nspcc-dev/neofs-node/files/10794809/obj-nn-test-node2.spb.yadro.com-s01-log.txt.zip)
[obj-nn-test-node2.spb.yadro.com-s02-log.txt.zip](https://github.com/nspcc-dev/neofs-node/files/10794812/obj-nn-test-node2.spb.yadro.com-s02-log.txt.zip)
[obj-nn-test-node2.spb.yadro.com-s03-log.txt.zip](https://github.com/nspcc-dev/neofs-node/files/10794815/obj-nn-test-node2.spb.yadro.com-s03-log.txt.zip)
[obj-nn-test-node2.spb.yadro.com-s04-log.txt.zip](https://github.com/nspcc-dev/neofs-node/files/10794816/obj-nn-test-node2.spb.yadro.com-s04-log.txt.zip)
## Version
```
0.35.0-47-gdea97133
```
## Your Environment
DEVENV
