### ISSUE TITLE
Couldn't add a storage node to the Network during local deploy.

### ISSUE THREAD

**Issue by masterSplinter01** [nspcc-dev/neofs-node#2274]
Tried to deploy the components locally, according to [neofs-node/deploy.md](https://github.com/nspcc-dev/neofs-node/blob/master/cmd/neofs-adm/docs/deploy.md) and [neo-go/consensus.md](https://github.com/nspcc-dev/neo-go/blob/master/docs/consensus.md).  Storage node is executed but is not presented on the network.

## Expected Behavior

 
Storage node is attached to the network.

## Current Behavior

 Storage node seems to be not attached: no node is on the network map, requests with `neofs-cli` fail.

## Steps to Reproduce (for bugs)

1. Start 1 consensus node 
2. Initialize sidechain with `neofs-adm`
3. Launch alphabet node
4. Execute storage node.  

Configs are below.

### Version used:
neofs-node (ir, adm, storadge): master e370aa9703e5829f8cbd6c11efbd09c333db7e98
neofs-cli: 
```
NeoFS CLI
Version: v0.35.0 
GoVersion: go1.17.13
```
neo-go: master 31ee21a83afc59ccb139b53398ebb6fc96b3d85a
### Server setup and configuration:

<details> 
<summary> Network config network.yml </summary>

```
rpc-endpoint: http://localhost:30333
alphabet-wallets: /home/kira/work/temp/alphabet-wallets
network:
  max_object_size: 67108864
  epoch_duration: 240
  basic_income_rate: 0
  homomorphic_hash_disabled: false
  fee:
    audit: 0
    candidate: 0
    container: 0
    container_alias: 0
    withdraw: 0
# if credentials section is omitted, then neofs-adm will require manual password input
credentials:
  az: "one"
  contract: "one"
```

</details>

<details>
<summary>Consensus node `protocol.privnet.yml`</summary>

```
ProtocolConfiguration:
  Magic: 56753
  MaxTraceableBlocks: 200000
  TimePerBlock: 1s
  MemPoolSize: 50000
  StandbyCommittee:
    - 03a2dd530c839bc8b74bfc71e3be797b9be6bbecd76512a9dbc26b32dc692f71fc
  ValidatorsCount: 1
  SeedList:
    - node_single:20333
  VerifyTransactions: true
  P2PSigExtensions: true
  NativeActivations:
    Notary: [0]
    ContractManagement: [0]
    StdLib: [0]
    CryptoLib: [0]
    LedgerContract: [0]
    NeoToken: [0]
    GasToken: [0]
    PolicyContract: [0]
    RoleManagement: [0]
    OracleContract: [0]

ApplicationConfiguration:
  SkipBlockVerification: false
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','boltdb'
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "/home/kira/work/temp/db"
  #    BoltDBOptions:
  #      FilePath: "./chains/privnet.bolt"
  P2P:
    Addresses:
      - ":20333" # in form of "[host]:[port][:announcedPort]"
    DialTimeout: 3s
    ProtoTickInterval: 2s
    PingInterval: 30s
    PingTimeout: 90s
    MaxPeers: 10
    AttemptConnPeers: 5
    MinPeers: 0
  Relay: true
  Oracle:
    Enabled: false
    AllowedContentTypes:
      - application/json
    Nodes:
      - http://localhost:30333
    RequestTimeout: 5s
    UnlockWallet:
      Path: "/wallet1_solo.json"
      Password: "one"
  P2PNotary:
    Enabled: true
    UnlockWallet:
      Path: "/home/kira/work/temp/alphabet-wallets/az.json"
      Password: "one"
  UnlockWallet:
      Path: "/home/kira/work/temp/alphabet-wallets/az.json"
      Password: "one"
  RPC:
    Enabled: true
    Addresses:
      - ":30333"
    EnableCORSWorkaround: false
    MaxGasInvoke: 100
  Consensus:
    Enabled: true
    UnlockWallet:
      Path: "/home/kira/work/temp/alphabet-wallets/az.json"
      Password: "one"
```

</details>

<details>
<summary>IR config</summary>

```
wallet:
  path: /home/kira/work/temp/alphabet-wallets/az.json                # Path to NEP-6 NEO wallet file
  password: "one"                            # Account password in the wallet

without_mainnet: false # Run application in single chain environment without mainchain

morph:
  dial_timeout: 10m # Timeout for RPC client connection to sidechain
  endpoint:
    client: # List of websocket RPC endpoints in sidechain
      - address: ws://localhost:30333/ws
  validators: # List of hex-encoded 33-byte public keys of sidechain validators to vote for at application startup
    - 03a2dd530c839bc8b74bfc71e3be797b9be6bbecd76512a9dbc26b32dc692f71fc
  switch_interval: 2m # interval b/w RPC switch attempts if the node is not connected to the highest priority node

mainnet:
  dial_timeout: 10m # Timeout for RPC client connection to mainchain; ignore if mainchain is disabled
  switch_interval: 2m # interval b/w RPC switch attempts if the node is not connected to the highest priority node
  endpoint:
    client: # List of websocket RPC endpoints in mainchain; ignore if mainchain is disabled
      - address: ws://localhost:30333/ws

control:
  grpc:
    endpoint: localhost:16512  # Endpoint that is listened by the control service; disabled by default

node:
  persistent_state:
    path: .neofs-ir-state # Path to application state file

locode:
  db:
    path: /home/kira/work/temp/locode/locode_db # Path to UN/LOCODE database file

timers:
  emit: 240 # Number of sidechain blocks between GAS emission cycles; disabled by default
  stop_estimation:
    mul: 1 # Multiplier in x/y relation of when to stop basic income estimation within the epoch
    div: 4 # Divider in x/y relation of when to stop basic income estimation within the epoch
  collect_basic_income:
    mul: 1 # Multiplier in x/y relation of when to start basic income asset collection within the epoch
    div: 2 # Divider in x/y relation of when to start basic income asset collecting within the epoch
  distribute_basic_income:
    mul: 3 # Multiplier in x/y relation of when to start basic income asset distribution within the epoch
    div: 4 # Divider in x/y relation of when to start basic income asset distribution within the epoch

emit:
  storage:
    amount: 800000000 # Fixed8 value of sidechain GAS emitted to all storage nodes once per GAS emission cycle; disabled by default
  mint:
    value: 20000000  # Fixed8 value of sidechain GAS transferred to account that received a deposit from mainchain
    cache_size: 1000 # LRU cache size of all deposit receivers to avoid double GAS emission
    threshold: 1     # Lifetime of records in LRU cache of all deposit receivers in NeoFS epochs
  gas:
    balance_threshold: 100000000000 # Fixed8 value of inner ring wallet balance threshold when GAS emission for deposit receivers is disabled; disabled by default

audit:
  timeout:
    get: 5s       # Timeout for object.Get operation during data audit
    head: 5s      # Timeout for object.Head operation during data audit
    rangehash: 5s # Timeout for object.RangeHash operation during data audit
    search: 10s   # Timeout for object.Search operation during data audit
  task:
    exec_pool_size: 10   # Number of workers to process audit routine in parallel
    queue_capacity:  100 # Maximum amount of simultaneous audit jobs
  pdp:
    pairs_pool_size: 10    # Number of workers to process PDP part of data audit in parallel
    max_sleep_interval: 5s # Maximum timeout between object.RangeHash requests to the storage node
  por:
    pool_size: 10 # Number of workers to process PoR part of data audit in parallel

indexer:
  cache_timeout: 15s # Duration between internal state update about current list of inner ring nodes

netmap_cleaner:
  enabled: false # Enable voting for removing stale storage nodes from network map
  threshold: 3  # Number of NeoFS epoch without bootstrap request from storage node before it considered stale

contracts:
  neofs: 7b08e83e3ffba3707d99471436787031bbe1cecf
  processing: 3b1af96deda6628a51e7bf496c10f47284308eee
  proxy: 2680860ce7b3e03c3fb030358cd5de17c33f438c
  alphabet:
    amount: 1                                         # Optional: override amount of alphabet contracts

logger:
  level: debug
```

</details>

<details>
<summary>Storage node config</summary>

```
node:
  wallet:
    path: "/home/kira/work/temp/sn01.json"  # path to a NEO wallet; ignored if key is presented
    address: NdkTc7SNpMijWfMFdiQgyKBwXHrdWrB49C
    password: ""  # password for a NEO account in the wallet; ignored if key is presented
  addresses:  # list of addresses announced by Storage node in the Network map
    - localhost:8080
  attribute_0: "Price:11"
  attribute_1: UN-LOCODE:RU MSK
  relay: true  # start Storage node in relay mode without bootstrapping into the Network map
  subnet:
    exit_zero: true # toggle entrance to zero subnet (overrides corresponding attribute and occurrence in `entries`)
    entries: # list of IDs of subnets to enter in a text format of NeoFS API protocol (overrides corresponding attributes)
      - 123
      - 456
      - 789
  notification:
    enabled: false  # turn on object notification service
    endpoint: "tls://localhost:4222"  # notification server endpoint
    timeout: "6s"  # timeout for object notification client connection
    default_topic: "topic"  # default topic for object notifications if not found in object's meta
    certificate: "/cert/path"  # path to TLS certificate
    key: "/key/path"  # path to TLS key
    ca: "/ca/path"  # path to optional CA certificate

grpc:
  - endpoint: localhost:8080  # endpoint for gRPC server

tree:
  enabled: true
  cache_size: 15
  replication_worker_count: 32
  replication_channel_capacity: 32
  replication_timeout: 5s
  sync_interval: 1h

control:
  grpc:
    endpoint: localhost:8090  # endpoint that is listened by the Control Service

morph:
  dial_timeout: 30s  # timeout for side chain NEO RPC client connection
  cache_ttl: 15s  # Sidechain cache TTL value (min interval between similar calls). Negative value disables caching.
                  # Default value: block time. It is recommended to have this value less or equal to block time.
                  # Cached entities: containers, container lists, eACL tables.
  switch_interval: 3m # interval b/w RPC switch attempts if the node is connected not to the highest priority node
  rpc_endpoint:  # side chain NEO RPC endpoints; are shuffled and used one by one until the first success
    - address: ws://localhost:30333/ws

apiclient:
  dial_timeout: 15s  # timeout for NEOFS API client connection
  stream_timeout: 20s # timeout for individual operations in a streaming RPC
  allow_external: true # allow to fallback to addresses in `ExternalAddr` attribute
  reconnect_timeout: 30s # time to wait before reconnecting to a failed node

policer:
  head_timeout: 15s  # timeout for the Policer HEAD remote operation

replicator:
  put_timeout: 15s  # timeout for the Replicator PUT remote operation (defaults to 1m)
  pool_size: 10     # maximum amount of concurrent replications

object:
  put:
    pool_size_remote: 100  # number of async workers for remote PUT operations

storage:
  # note: shard configuration can be omitted for relay node (see `node.relay`)
  shard_pool_size: 15 # size of per-shard worker pools used for PUT operations
  shard_ro_error_threshold: 100 # amount of errors to occur before shard is made read-only (default: 0, ignore errors)

  shard:
    default: # section with the default shard parameters
      resync_metabase: true  # sync metabase with blobstor on start, expensive, leave false until complete understanding

      writecache:
        enabled: true
        small_object_size: 16k  # size threshold for "small" objects which are cached in key-value DB, not in FS, bytes
        max_object_size: 134217728  # size threshold for "big" objects which bypass write-cache and go to the storage directly, bytes
        workers_number: 30  # number of write-cache flusher threads

      metabase:
        perm: 0644  # permissions for metabase files(directories: +x for current user and group)
        max_batch_size: 200
        max_batch_delay: 20ms

      pilorama:
        max_batch_delay: 5ms # maximum delay for a batch of operations to be executed
        max_batch_size: 100 # maximum amount of operations in a single batch

      compress: false  # turn on/off zstd(level 3) compression of stored objects
      small_object_size: 100 kb  # size threshold for "small" objects which are cached in key-value DB, not in FS, bytes

      blobstor:
        - size: 4m  # approximate size limit of single blobovnicza instance, total size will be: size*width^(depth+1), bytes
          perm: 0644  # permissions for blobstor files(directories: +x for current user and group)
          depth: 1  # max depth of object tree storage in key-value DB
          width: 4   # max width of object tree storage in key-value DB
          opened_cache_capacity: 50  # maximum number of opened database files
        - perm: 0644  # permissions for blobstor files(directories: +x for current user and group)
          depth: 5  # max depth of object tree storage in FS

      gc:
        remover_batch_size: 200  # number of objects to be removed by the garbage collector
        remover_sleep_interval: 5m  # frequency of the garbage collector invocation

    0:
      mode: read-write  # mode of the shard, must be one of the:
        # read-write (default)
        # read-only
        # degraded
        # degraded-read-only
        # disabled (do not work with the shard, allows to not remove it from the config)
      resync_metabase: false  # sync metabase with blobstor on start, expensive, leave false until complete understanding

      writecache:
        enabled: false
        no_sync: true
        path: /home/kira/work/temp/storage/0/cache  # write-cache root directory
        capacity: 3221225472  # approximate write-cache total size, bytes

      metabase:
        path: /home/kira/work/temp/storage/0/meta  # metabase path
        max_batch_size: 100
        max_batch_delay: 10ms

      compress: true  # turn on/off zstd(level 3) compression of stored objects
      compression_exclude_content_types:
        - audio/*
        - video/*

      blobstor:
        - type: blobovnicza
          path: /home/kira/work/temp/storage/0/blob/blobovnicza
        - type: fstree
          path: tmp/0/blob  # blobstor path

      pilorama:
        path: /home/kira/work/temp/storage/0/blob/pilorama.db # path to the pilorama database. If omitted, `pilorama.db` file is created blobstor.path
        max_batch_delay: 10ms
        max_batch_size: 200

      gc:
        remover_batch_size: 150  # number of objects to be removed by the garbage collector
        remover_sleep_interval: 2m  # frequency of the garbage collector invocation
 
logger:
  level: debug
```

</details>

### Operating System and version (`uname -a`):
```
$ uname -a           
Linux kira-20n4000brt 5.15.93-1-MANJARO #1 SMP PREEMPT Thu Feb 9 12:13:18 UTC 2023 x86_64 GNU/Linux
```

## Log files

[node.log](https://github.com/nspcc-dev/neofs-node/files/10861881/node.log)
[ir.log](https://github.com/nspcc-dev/neofs-node/files/10861882/ir.log)
[cn.log](https://github.com/nspcc-dev/neofs-node/files/10861883/cn.log)
