### ISSUE TITLE
Move to using "Github Actions" for test reports (instead of gh-pages)

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2324]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I'm looking at the gh-pages branch.

## Describe the solution you'd like
No gh-pages branch. Looks like "Github Actions" for Pages can give us that.

**Comment by roman-khimov** [comment]
> Получение объектов: 100% (17083/17083), 51.14 МиБ | 7.34 МиБ/с, готово.
> Из github.com:nspcc-dev/neofs-node
>   29cafd203..570e2ad54  gh-pages      -> origin/gh-pages

**Comment by roman-khimov** [comment]
That's the example GH generates on its own:
```
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
That's the reference action (with all the requirements): https://github.com/actions/upload-pages-artifact

Can we make something out of it?
