### ISSUE TITLE
missing port in address

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#2420]
This:
```Yaml
morph:
  seed_nodes:
    - hostA
    - hostB
    - hostC
```

gives an error:
```
invalid blockchain configuration: invalid seed nodes 'morph.consensus.seed_nodes' (TCP addresses): address hostA: missing port in address
```

1. assign a port
2. use it by default
