### ISSUE TITLE
Rework shard path configurations

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2497]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I'm looking at the storage node config:
```
storage:
  shard:
    0:
      blobstor:
      - path: /srv/neofs/data0/blobovnicza
        type: blobovnicza
      - path: /srv/neofs/data0/tree
        type: fstree
      metabase:
        path: /srv/neofs/meta/metabase0.db
      writecache:
        path: /srv/neofs/meta/writecache0
    1:
      blobstor:
      - path: /srv/neofs/data1/blobovnicza
        type: blobovnicza
      - path: /srv/neofs/data1/tree
        type: fstree
      metabase:
        path: /srv/neofs/meta/metabase1.db
      writecache:
        path: /srv/neofs/meta/writecache1
    2:
      blobstor:
      - path: /srv/neofs/data2/blobovnicza
        type: blobovnicza
      - path: /srv/neofs/data2/tree
        type: fstree
      metabase:
        path: /srv/neofs/meta/metabase2.db
      writecache:
        path: /srv/neofs/meta/writecache2
...
```
What we want to configure here is:
 * three disks that store data
 * one disk that stores metabase(s)
 * one disk that is used for write caches

What we have in the configuration is:
 * separate path to bbcz and fstree
 * three metabases
 * three write caches

It easily leads to duplication and confusion. Of course it gives some additional flexibility, yet at the same time it's never needed. 

## Describe the solution you'd like
What it may look like:
```
storage:
  metabase:
    path: /srv/neofs/ssd/meta
  writecache:
    path: /srv/neofs/ssd/writecache
  shard:
    0:
      blobstor:
      - path: /srv/neofs/data0/
        type: bbcz+fstree
    1:
      blobstor:
      - path: /srv/neofs/data1/
        type: bbcz+fstree
    2:
      blobstor:
      - path: /srv/neofs/data2/
        type: bbcz+fstree
...
```
And never ever `MkdirAllX`, these directories must exist and then the node takes full control over them.

CC @532910.
