### ISSUE TITLE
bbcz to peapod migration failed to update the config

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2572]
## Expected Behavior
A new config is generated with bbcz settings replaced to peapod.

## Current Behavior
```
2023/09/13 16:41:44 unexpected 'storage' section type: map[string]interface {} instead of map[interface {}]interface {}
```

## Steps to Reproduce (for bugs)
```
storage:
  shard:
    0:
      blobstor:
      - path: /srv/neofs/data0/blobovnicza
        type: blobovnicza
      - path: /srv/neofs/data0/tree
        type: fstree
      metabase:
        path: /srv/neofs/meta/metabase0.db
      writecache:
        path: /srv/neofs/meta/writecache0
    1:
      blobstor:
      - path: /srv/neofs/data1/blobovnicza
        type: blobovnicza
      - path: /srv/neofs/data1/tree
        type: fstree
      metabase:
        path: /srv/neofs/meta/metabase1.db
      writecache:
        path: /srv/neofs/meta/writecache1
    default:
      blobstor:
      - depth: 1
        opened_cache_capacity: 50
        perm: '0644'
        size: 4gb
        width: 4
      - depth: 5
        perm: '0644'
      compress: true
      gc:
        remover_batch_size: 100
        remover_sleep_interval: 1m
      metabase:
        max_batch_delay: 20ms
        max_batch_size: 200
        perm: '0640'
      pilorama:
        max_batch_delay: 5ms
        max_batch_size: 100
      resync_metabase: false
      small_object_size: 100 kb
      writecache:
        capacity: 3gb
        enabled: true
        max_object_size: 128mb
        small_size: 32kb
        workers_number: 30
  shard_ro_error_threshold: 0
```

## Your Environment
* Version used: 6f4128f2bcbe6a1c719102c27697dc0fd13d60cc
