### ISSUE TITLE
Node fails to connect to secondary RPCs during startup

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2986]
## Expected Behavior
Nodes going over all of the `morph.endpoints` list for connection attempts.

## Current Behavior
Looks like only the first one is tried during startup, because with a configuration of
```
morph:
  endpoints:
    - ws://192.168.43.87:30333/ws
    - ws://192.168.43.88:30333/ws
    - ws://192.168.43.89:30333/ws
    - ws://192.168.43.90:30333/ws
    - ws://192.168.43.91:30333/ws
    - ws://192.168.43.85:30333/ws
    - ws://192.168.43.86:30333/ws
  dial_timeout: 20s
```
and 100 nodes starting (with 7 blockchain nodes available) only 60 are able to connect to the first one while all the others just fail with
```
2024-10-28T21:26:08.752Z	info	neofs-node/config.go:665	failed to create neo RPC client	{"endpoints": ["ws://192.168.43.87:30333/ws", "ws://192.168.43.88:30333/ws", "ws://192.168.43.89:30333/ws", "ws://192.168.43.90:30333/ws", "ws://192.168.43.91:30333/ws", "ws://192.168.43.85:30333/ws", "ws://192.168.43.86:30333/ws"], "error": "could not create RPC client: WS client creation: Internal error (-32603) - websocket users limit reached"}
```

## Possible Solution
Restore the expected behavior, do not fail immediately, walk through the list.

## Regression
No.

## Your Environment
* Version used: 0.43.0
* Operating System and version (`uname -a`): Ubuntu stable
