### ISSUE TITLE
Healthchecks in private node API

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#306]
Design private API service in storage node with healthcheck function.

### Endpoint 

Private API GRPC service hosted on separate endpoint

```yaml
grpc:
  public_endpoint: 82.15.23.41:30333
  private_endpoint: 127.0.0.1:2002
```

However both public and private endpoints can share a value. 

### Authentication 

Private API considers control plane operations. So we need some authentication. Simplest way is authenticate by key-pair.
Consider having an allow-list of public keys in node configuration

```yaml
private:
  permitted_keys:
    - 02f7528ce97c9a93558efe7d4f62577aabdf771c931f54a71be6ad21e7d9cc1777
    - 0340750b92789821683283bcb98e32b7e032b94f267b6964613fc31a7ce5813fdd
```

### Healthcheck

Healthcheck should return state structure, defined in private API. For now it should contain status of the node: offline or online. Probably it should be enum to increase amount of states in the future.
