### ISSUE TITLE
Resync meta test failure

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#3188]
## Expected Behavior
Green.

## Current Behavior
 tests.failovers.test_failover_part.TestFailoverNodePart#test_enable_resync_metabase_delete_metadata constantly failing for 0.45.0:
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/879-1740743256/index.html#suites/4b9f0852769b4f47c7f6f0b89053e5e7/f8974127a84cf1c7/
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/879-1740743339/index.html#suites/4b9f0852769b4f47c7f6f0b89053e5e7/1caa761553924527/
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/880-1740754030/index.html#suites/4b9f0852769b4f47c7f6f0b89053e5e7/11cd7ea9bedf31d7/
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/880-1740754239/index.html#suites/4b9f0852769b4f47c7f6f0b89053e5e7/bf57a10c420d529/
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/885-1740804435/index.html#suites/4b9f0852769b4f47c7f6f0b89053e5e7/c0d42efece0ee0e8/

## Possible Solution
Fix it.

## Regression
Looks like.

## Your Environment
* Version used: 0.45.0

**Comment by cthulhu-rider** [comment]
1st run SN config:
```yaml
storage:
  shard:
    0:
      blobstor: 
        - type: peapod
          path: /home/ll/projects/neo/testcases/test-run-2025-03-01-14-07-06-133910/env_files/neofs-env-2025-03-01-14-09-49/sn_1_wvxbymcaiu/shard_blobovnicza_xftsieekqr  # Blobovnicza root directory 
        - type: fstree
          path: /home/ll/projects/neo/testcases/test-run-2025-03-01-14-07-06-133910/env_files/neofs-env-2025-03-01-14-09-49/shards/shard_fstree_vrmbrkxyee  # FSTree root directory
          depth: 2
    1:
      blobstor: 
        - type: peapod
          path: /home/ll/projects/neo/testcases/test-run-2025-03-01-14-07-06-133910/env_files/neofs-env-2025-03-01-14-09-49/sn_1_wvxbymcaiu/shard_blobovnicza_onldthbnlr  # Blobovnicza root directory 
        - type: fstree
          path: /home/ll/projects/neo/testcases/test-run-2025-03-01-14-07-06-133910/env_files/neofs-env-2025-03-01-14-09-49/shards/shard_fstree_vydqlcglwn  # FSTree root directory
          depth: 2
```

then SN is stopped and restarted with the next one:
```yaml
storage:
  shard:
    0:
      blobstor: 
        - type: fstree
          path: /home/ll/projects/neo/testcases/test-run-2025-03-01-14-07-06-133910/env_files/neofs-env-2025-03-01-14-09-49/shards/shard_fstree_vrmbrkxyee  # FSTree root directory
          depth: 2
    1:
      blobstor: 
        - type: fstree
          path: /home/ll/projects/neo/testcases/test-run-2025-03-01-14-07-06-133910/env_files/neofs-env-2025-03-01-14-09-49/shards/shard_fstree_vydqlcglwn  # FSTree root directory
          depth: 2
```

where did `peapod` go? The object was saved into it on 1st run:
```
info	log/log.go:12	local object storage operation	{"shard_id": "83A34x4ioH7VLsJD8E1zCP", "address": "82ER584cjYRDdYHsXqvohAjtVbuj31vxYNUj5VAbMJAW/2fG3ZXUmWt55goK6MG2BP2hZT7pmb5VXPgqWHpTAwhpG", "op": "PUT", "type": "peapod", "storage_id": "peapod"}
```

if we restart w/o peapod, object becomes unavailable obviously

@evgeniiz321
