### ISSUE TITLE
Support NEP-6 wallets as a private key source in neofs nodes

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#562]
Related to #491 

We've got wallet support in NeoFS CLI (#466) and it should be supported in inner ring and storage nodes too. This is going to be a first step to drop neofs-crypto dependency. 

Storage node config can look like that:
```yaml
node:
  wallet:
    path: /home/user/node/wallet.json
    address: NXWry4f4LJ1ynrzaPjzfhG7KSh5aBSaqWU
    password: hunter2
```

We can keep `node.key` parameter for backward compatibility, but should move key file reading logic out of neofs-crypto library (`crypto.LoadPrivateKey`). If both wallet and key parameters are present, use key parameter.

Summary:
- [ ] Add NEP-6 wallet support in Storage Node
- [ ] Add NEP-6 wallet support in Inner Ring
- [ ] Figure out what needs to be done to remove neofs-crypto dependency from node
