### ISSUE TITLE
WriteCache maxDBSize param is not used

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#734]
There is `NEOFS_STORAGE_SHARD_X_WRITECACHE_DB_SIZE` config value, `WithMaxDBSize` option for `writecache` constructor and commentaries in code that claim that param is used for smth, but it seems that it is read and... that is all.

**Comment by alexvanin** [comment]
I think we can drop it, because we use `mem_size` as max memory size config parameter in config.
```yaml
storage:
  shard:
    0:
      writecache:
        mem_size: xxx
```

/cc @fyrchik
