### ISSUE TITLE
describe config parameters

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#858]
My notes after talking with @cthulhu-rider :

```YAML

# All sizes are in bytes, multiplicative suffixes are not supported yet.

refill_metabase: false          # sync metabase with blobstore on start, expensive, leave false untill complete understanding

writecache:
  path: tmp/0/cache             # writecache root directory
  mem_size: 2147483648          # coarse RAM usage limit for small objects
  small_size: 16384             # small objects goes to boltdb (leave default)
  max_size: 134217728           # objects bigger that <max_size> bypassing writecache and goes to storage directly
  workers_number: 30            # thread number of writecache flushers 
  size_limit: 3221225472        # coarse writecache total size (5% of metabase part is a good start)

metabase:
  path: tmp/0/meta              #
  perm: 0644                    #

blobstor:
  path: tmp/0/blob              #
  perm: 0644                    #
  compress: true                # zstd, level 3, unconfigurable right now
  shallow_depth: 5              # directory structure depth
  small_size_limit: 102400      # bigger objects goes to filesystem, smaller -- into blobovnicza

blobovnicza:
  size: 4194304                 # coarse one db size limit, total size: size*width^(depth+1), 5% of blobstor is a good start)
  shallow_depth: 1              # directory structure depth
  shallow_width: 4              # and width
  opened_cache_size: 50         #  maximum number of opened database files

gc:                             # full object removal
  remover_batch_size: 150       # number of objects to remove 
  remover_sleep_interval: 2m    # frequency of invocation
```

This should be added to [config/example/node.yaml](https://github.com/nspcc-dev/neofs-node/blob/master/config/example/node.yaml) or documented somewhere else.
