### ISSUE TITLE
Need to verify: writecache max_size is not working

### ISSUE THREAD

**Issue by anatoly-bogatyrev** [nspcc-dev/neofs-node#866]
Version: v0.24.1

```
 writecache:
        path: /meta3/write_cache3
        mem_size: 1073741824
        db_size: 0
        small_size: 32768
        max_size: 67108864

```

As a result of the neofs-node work over load generator we observe:
```
/dev/nvme1n1p1  219G  219G     0 100% /meta0
/dev/nvme1n1p3  219G  219G     0 100% /meta2
/dev/nvme1n1p2  219G  219G     0 100% /meta1
/dev/nvme1n1p4  221G  221G     0 100% /meta3
```
