### ISSUE TITLE
Support shared shard parameters

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#877]
Originally posted by @aprasolova.

In some situations it would be convenient to configure the global parameters inherited by all shards (for example, with a large number of shards that differ only in file paths).
```
storage:
  shard_num: 2
  common:
    refill_metabase: false
    use_write_cache: false
    writecache:
        mem_size: 2147483648
        small_size: 16384
        max_size: 134217728
        workers_number: 30
        size_limit: 3221225472
    blobstor:
        perm: 0644
        compress: true
        shallow_depth: 5
        small_size_limit: 102400
        blobovnicza:
          size: 4194304
          shallow_depth: 1
          shallow_width: 4
          opened_cache_size: 50
    gc:
        remover_batch_size: 150
        remover_sleep_interval: 2m
        
  shard:
    0:     
      writecache:
        path: tmp/0/cache    

      metabase:
        path: tmp/0/meta
        perm: 0644

      blobstor:
        path: tmp/0/blob
    1:     
      writecache:
        path: tmp/1/cache    

      metabase:
        path: tmp/1/meta
        perm: 0644

      blobstor:
        path: tmp/1/blob
```
